name: StreamLink
version: '2.0'
main: com.taffy.streamlink.streamlink
api-version: '1.21'
commands:
  streamlink:
    description: StreamLink commands
    usage: /streamlink
    permission: streamlink.use
permissions:
  streamlink.use:
    description: Use player commands
    default: true
  streamlink.admin:
    description: Use admin tools (/setup, /migrate, /sync, /export, /debug, /streamlabs)
    default: op
resources:
  - config.yml